### ISSUE TITLE
Dark mode icon has incorrect position on the page in Mobile view

### ISSUE THREAD

**Issue by shimkiv** [huntabyte/mode-watcher#21]
https://www.shadcn-svelte.com is in use for the app.
Using documentation from here: https://www.shadcn-svelte.com/docs/dark-mode

**Steps**:
- Switch the theme to the Dark mode.

**Actual results**:
- Maybe it depends on some other preconditions and layouts/pages structure (to be determined if only happens on my end) but Dark mode icon has incorrect position on the page (please refer to the video attached).

**Expected results**:
- Dark mode icon is positioned inside the parent trigger.

---

Issue recording: https://www.youtube.com/shorts/REMenzzOMAc

**Comment by ollema** [comment]
your video is not loading for me, so I can't know what the problem is. maybe the video is in the encoding stage or something.

anyways, this is not a `mode-watcher` issue since `mode-watcher` is headless if you will, I would suggest that you close this issue and open a new one to (potentially) fix the documentation for dark mode docs in `shadcn-svelte`

**Comment by shimkiv** [comment]
@ollema I see, thanks for reply. Still weird to see this for dark mode icon only and only on mobile. Closing this one then...
