### ISSUE TITLE
Screen flickers white on initial page load when dark theme is selected.

### ISSUE THREAD

**Issue by niemyjski** [huntabyte/mode-watcher#43]
It's choosing the light theme on page load before dark mode is set. Is there a good work around for this?

**Comment by ollema** [comment]
is this still a problem @niemyjski?

if so, could you expand a bit on what the problem is? 

- are you experiencing FOUC - as in the page flashes with light mode for a split second while it's loading even though dark mode is set? if so, that could be a bug but maybe it's an issue on your end - see: https://github.com/huntabyte/mode-watcher/issues/39 it could be that you have an incompatible CSP policy for example

- or is your problem that `mode-watcher` defaults to the system mode, which could be light mode, if no user preference is saved in `localStorage`? if so, that is indeed fixed by the `defaultMode` prop

**Comment by niemyjski** [comment]
Yes, I'm trying to track it down still. It appears to be a FOUC and I only see it on my windows machine not my mac.  I'm setting the default mode to dark: https://github.com/exceptionless/Exceptionless/blob/main/src/Exceptionless.Web/ClientApp/src/routes/%2Blayout.svelte#L18 I noticed even with setting mode watcher to default mode dark, it still says system on user prefers mode.

**Comment by niemyjski** [comment]
I updated all deps / browser and I'm not seeing this occur (I update weekly). I'm going to keep a close eye on this and will reopen if I see it again. Really not sure what was causing it (but currently, don't have time to go back and dig in).
